const fs = require('fs')
const onix = require('./onix')

!(async () => {
  // console.log(await onix('./files/bw-audiobook-1.xml'))
  // console.log(await onix('./files/bw-epub-1.xml'))
  // console.log(await onix('./files/bw-epub-2.xml'))

  // console.log(await onix('./files/bw-teste1.xml'))
  // console.log(await onix('./files/bw-teste2.xml'))
  // console.log(await onix('./files/bw-teste3.xml'))
  // console.log(await onix('./files/bw-teste8.xml'))

  // fs.writeFileSync('./final-audiobook-1.json', JSON.stringify(await onix('./files/bw-audiobook-1.xml'), null, 2))
  // fs.writeFileSync('./final-epub-1.json', JSON.stringify(await onix('./files/bw-epub-1.xml'), null, 2))
  // fs.writeFileSync('./final-epub-2.json', JSON.stringify(await onix('./files/bw-epub-2.xml'), null, 2))

  fs.writeFileSync('./final-teste1.json', JSON.stringify(await onix('./files/bw-teste1.xml'), null, 2))
  fs.writeFileSync('./final-teste2.json', JSON.stringify(await onix('./files/bw-teste2.xml'), null, 2))
  fs.writeFileSync('./final-teste3.json', JSON.stringify(await onix('./files/bw-teste3.xml'), null, 2))
  fs.writeFileSync('./final-teste4.json', JSON.stringify(await onix('./files/bw-teste4.xml'), null, 2))
  fs.writeFileSync('./final-teste5.json', JSON.stringify(await onix('./files/bw-teste5.xml'), null, 2))
  fs.writeFileSync('./final-teste6.json', JSON.stringify(await onix('./files/bw-teste6.xml'), null, 2))
  fs.writeFileSync('./final-teste7.json', JSON.stringify(await onix('./files/bw-teste7.xml'), null, 2))
  fs.writeFileSync('./final-teste8.json', JSON.stringify(await onix('./files/bw-teste8.xml'), null, 2))
  fs.writeFileSync('./final-teste9.json', JSON.stringify(await onix('./files/bw-teste9.xml'), null, 2))
  fs.writeFileSync('./final-teste10.json', JSON.stringify(await onix('./files/bw-teste10.xml'), null, 2))
  fs.writeFileSync('./final-teste11.json', JSON.stringify(await onix('./files/bw-teste11.xml'), null, 2))
  fs.writeFileSync('./final-teste12.json', JSON.stringify(await onix('./files/bw-teste12.xml'), null, 2))
  fs.writeFileSync('./final-teste13.json', JSON.stringify(await onix('./files/bw-teste13.xml'), null, 2))
  fs.writeFileSync('./final-teste14.json', JSON.stringify(await onix('./files/bw-teste14.xml'), null, 2))
  fs.writeFileSync('./final-teste15.json', JSON.stringify(await onix('./files/bw-teste15.xml'), null, 2))
  fs.writeFileSync('./final-teste16.json', JSON.stringify(await onix('./files/bw-teste16.xml'), null, 2))
  fs.writeFileSync('./final-teste17.json', JSON.stringify(await onix('./files/bw-teste17.xml'), null, 2))
})()